# Generated by Django 3.0.5 on 2021-01-14 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_me', '0002_auto_20210103_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=500),
        ),
    ]
