# Generated by Django 3.0.5 on 2021-01-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_me', '0003_auto_20210114_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='questionText',
        ),
    ]
