# Generated by Django 3.0.5 on 2021-01-14 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_me', '0004_auto_20210114_2146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questionText',
            new_name='question_text',
        ),
    ]
