# Generated by Django 3.0.5 on 2021-01-14 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask_me', '0005_auto_20210114_2158'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='likes',
            new_name='approve',
        ),
    ]
