# Generated by Django 3.0.5 on 2021-01-16 15:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ask_me', '0006_auto_20210114_2228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('question_text', 'pub_date')},
        ),
        migrations.AddField(
            model_name='answer',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 16, 15, 51, 17, 913364, tzinfo=utc), verbose_name='Date posted'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Date published'),
        ),
    ]
