# Generated by Django 3.0.5 on 2021-06-02 15:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ask_me', '0007_auto_20210116_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='answer',
            name='posted_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date posted'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(),
        ),
    ]
