# Generated by Django 3.0.5 on 2021-06-05 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_me', '0008_auto_20210602_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='disapprove',
            field=models.IntegerField(default=0),
        ),
    ]
