# Generated by Django 3.2.3 on 2021-07-31 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.TextField()),
                ('pubDate', models.DateTimeField(verbose_name='Date published')),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('questionText', 'pubDate'),
            },
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('wordName', models.CharField(max_length=200)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('meaning', models.CharField(blank=True, max_length=500, null=True)),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.word')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(default=None)),
                ('approve', models.IntegerField(default=0)),
                ('disapprove', models.IntegerField(default=0)),
                ('postedOn', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date posted')),
                ('updatedAt', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.question')),
            ],
        ),
    ]
